-- MySQL Script generated by MySQL Workbench
-- sáb 19 abr 2025 18:08:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema punkrecords
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema punkrecords
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `punkrecords` ;
USE `punkrecords` ;

-- -----------------------------------------------------
-- Table `punkrecords`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punkrecords`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(80) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `user_img` VARCHAR(128) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punkrecords`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punkrecords`.`favorites` (
  `favorite_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `media_name` VARCHAR(256) NOT NULL,
  `media_id` INT NOT NULL,
  `media_type` VARCHAR(45) NOT NULL,
  `finished` BIT NOT NULL DEFAULT false,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`favorite_id`),
  UNIQUE INDEX `favorite_id_UNIQUE` (`favorite_id` ASC) VISIBLE,
  INDEX `fk_favorites_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `punkrecords`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punkrecords`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punkrecords`.`reviews` (
  `review_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `review` VARCHAR(500) NULL,
  `date` DATE NOT NULL,
  `favorite_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`review_id`),
  UNIQUE INDEX `review_id_UNIQUE` (`review_id` ASC) VISIBLE,
  INDEX `fk_reviews_favorites1_idx` (`favorite_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_favorites1`
    FOREIGN KEY (`favorite_id`)
    REFERENCES `punkrecords`.`favorites` (`favorite_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
